Clothing_Template = {
    'weight_column': 'F',
    'start_row': 10,
    'total_row': 40,
    'bag_count_cell': 'B40',
    'date_cell': 'A3',
    'lot_number_cell': 'B3',
    'name_cell': 'C2',
    'address_cell': 'C3',
    'date': None,
    'lot_number': None,
    'name': None,
    'address': None,
    'bag_count': None,
    'target_weight': None,
}
